//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assessment1.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public decimal RatePerHour { get; set; }

        public decimal CalculateWage(decimal hours)
        {
            return Decimal.Multiply(this.RatePerHour, hours);
        }

        public decimal CalculateTax(decimal hours)
        {
            return Decimal.Multiply(this.CalculateWage(hours), Decimal.Parse("19.20")) / 100;
        }

        public virtual Accountant Accountant { get; set; }
        public virtual Technician Technician { get; set; }
    }
}
